apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinot-operator-role
rules:
  - apiGroups: ["pinot.apache.org"]
    resources: ["pinotclusters", "pinotclusters/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
