# This rule is not used by the project pinot-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to pinot.apache.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pinot-operator
    app.kubernetes.io/managed-by: kustomize
  name: pinotcluster-viewer-role
rules:
- apiGroups:
  - pinot.apache.org
  resources:
  - pinotclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pinot.apache.org
  resources:
  - pinotclusters/status
  verbs:
  - get
